<?php

namespace ContainerCOxcvY5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WdWIHHAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wdWIHHA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wdWIHHA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'request' => ['privates', '.errored..service_locator.wdWIHHA.Symfony\\Component\\BrowserKit\\Request', NULL, 'Cannot autowire service ".service_locator.wdWIHHA": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'request' => 'Symfony\\Component\\BrowserKit\\Request',
        ]);
    }
}
