controllers:
    resource: ../src/Controller/
    type: attribute
route_accueil:
    path: /accueil
    controller: App\Controller\EtudiantController::index
EtudiantAjouter:
    path: /etudiant/ajouter
    controller: App\Controller\EtudiantController::ajouter