<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUOmSXWI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUOmSXWI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUOmSXWI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUOmSXWI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUOmSXWI\App_KernelDevDebugContainer([
    'container.build_hash' => 'UOmSXWI',
    'container.build_id' => '8a2b8c22',
    'container.build_time' => 1668421007,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUOmSXWI');
